// react-admin-ts/src/pages/admin-user/AdminUserCreate.tsx
import { useState, ChangeEvent, FormEvent } from "react";
import { Link } from "react-router-dom";
import InputField from "../../components/InputField";
import { useStoreAdminUser } from "./hooks/useStoreAdminUser";

function AdminUserCreate() {
  const [full_name, setFullName] = useState<string>("Admin 3");
  const [email, setEmail] = useState<string>(
    "admin" + new Date().getMinutes() + new Date().getSeconds() + "@admin.com"
  );
  const [image, setImage] = useState<File | null>(null);
  const { mutate } = useStoreAdminUser();

  const handleProfileImageChange = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files ? e.target.files[0] : null;
    setImage(file);
  };

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData();

    const data = {
      email,
      password: "", // Add the missing properties with empty values
      name: "",
      role: "",
      avatar: "",
    };

    Object.entries(data).forEach(([key, value]) => {
      formData.append(key, value);
    });

    if (image) {
      formData.append("image", image);
    }

    mutate(formData);
  };

  return (
    <div className="flex-1 bg-white">
      <div className="px-5 pl-64">
        <div className="w-full">
          <div className="block rounded-lg p-6">
            <h1 className="text-xl font-semibold mb-4 text-gray-900 dark:text-gray-100">
              Admin User Information
              {JSON.stringify(image)}
            </h1>
            {/*<p className="text-gray-600 dark:text-gray-300 mb-6">Use a permanent address where you can*/}
            {/*    receive mail.</p>*/}
            <form onSubmit={handleSubmit}>
              <div className="mb-4">
                <InputField
                  label="Full Name"
                  type="text"
                  name="full_name"
                  value={full_name}
                  onChange={(e) => setFullName(e.target.value)}
                  autoFocus
                  errorMessages={[]}
                />
              </div>
              <div className="mb-4">
                <InputField
                  label="Email Address"
                  type="email"
                  name="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  autoFocus
                  errorMessages={[]}
                />
              </div>
              <div className="mb-4">
                <InputField
                  accept="image/*"
                  label="Profile Photo"
                  type="file"
                  name="image"
                  onChange={handleProfileImageChange}
                  value={""}
                  errorMessages={[]}
                />
              </div>

              <div className="flex items-center">
                <button
                  type="submit"
                  className="bg-primary-600 py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
                >
                  Save
                </button>
                <Link
                  to="/admin/admin-user"
                  className="ml-auto font-medium text-gray-600 hover:text-gray-500"
                >
                  Cancel
                </Link>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}

export default AdminUserCreate;

// backend/src/views/AdminUserCreate.vue
<template>
    <div class="mx-auto max-w-screen-xl mt-3 mb-5">
        <div class="sm:flex sm:items-center sm:justify-between">
            <div class="text-center sm:text-left">
                <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">
                    Create Admin User
                </h1>
            </div>
        </div>
    </div>

    <div class="overflow-x-auto text-left border-t my-8 text-sm">
        <form @submit.prevent="submit" action="#" class="mt-3 w-full">
          <div class="w-full">
            <label for="Email" class="w-full text-sm font-medium text-gray-700">
              Email
            </label>

            <input
              type="email"
              v-model="email"
              autofocus
              id="Email"
              name="email"
              class="mt-1 block w-full rounded-md border-gray-200 bg-white text-sm text-gray-700 shadow-sm"
            />
          </div>

          <div class="mt-5">
            <label
              for="Password"
              class="block text-sm font-medium text-gray-700"
            >
              Password
            </label>

            <input
              type="password"
              id="Password"
              v-model="password"
              name="password"
              class="mt-1 w-full rounded-md border-gray-200 bg-white text-sm text-gray-700 shadow-sm"
            />
          </div>

          <div class="mt-5 flex w-full items-center">
            <button
              type="submit"
              class="shrink-0 rounded-md border border-blue-600 bg-blue-600 px-8 py-3 text-sm font-medium text-white transition hover:bg-transparent hover:text-blue-600 focus:outline-none focus:ring active:text-blue-500"
            >
              Create Admin User
            </button>
          </div>
        </form>
       
    </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'

const email = ref('')
const password = ref('')
const submit = () => {
    console.log(email, password)
}
// const showPassword = ref<boolean>(false)
</script>
