// react-admin/src/pages/auth/Login.tsx
import logo from "../../assets/logo_only.svg";
import {  Link } from "react-router-dom";
import InputField from "../../components/InputField";
import {SubmitHandler, useForm} from "react-hook-form";
import { joiResolver } from "@hookform/resolvers/joi";
import { useLogin } from "./hooks/useLogin";
import { loginSchema } from "./schemas/login.schema";
import ErrorMessage from "../../components/ErrorMessage";
import { useTranslation } from "react-i18next";
import ILoginPost from "../../types/auth/ILoginPost";
import i18next from "i18next";
import {changeLocale} from "../../lib/common";

function Login() {
  const [t, i18n] = useTranslation("global");
  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm<ILoginPost>({
    resolver: joiResolver(loginSchema),
  })
  const {
    mutate,
    isPending,
    error
  } = useLogin()

  const submitHandler: SubmitHandler<ILoginPost> = (data) => {
    mutate(data);
  };

  return (
    <div className="min-h-screen bg-slate-100 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
      <div className="flex justify-center">
        <img src={logo} className="w-20 h-20" alt="Avored Rust Cms" />
      </div>

      <div className="sm:mx-auto sm:w-full sm:max-w-md">
        <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
          {t("sign_into_your_account")}
        </h2>
      </div>
      <div></div>

      <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
        <div className="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
          <form onSubmit={handleSubmit(submitHandler)} className="space-y-5">
            <div>
              <InputField
                label={t("email_address")}
                type="text"
                name="email"
                autoFocus={true}
                register={register("email")}
              />
              <ErrorMessage frontendErrors={errors} backendErrors={error} identifier="email" />
            </div>
            <div>
              <InputField
                label={t("password")}
                type="password"
                name="password"
                register={register("password")}
              />
              <ErrorMessage frontendErrors={errors} backendErrors={error} identifier="password" />
            </div>
            <div className="flex items-center justify-end">
              <div className="text-sm">
                <Link
                  to={`/admin/forgot-password`}
                  className="font-medium text-primary-600 hover:text-primary-500"
                >
                  {t("forgot_your_password")}
                </Link>
              </div>
            </div>

            <div>
              <button
                type="submit"
                className="group relative bg-primary-600 w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
              >
                {isPending ? "Loading..." : t("sign_in")}
              </button>
            </div>

            <div className="text-gray-600 text-center text-sm">
              {t("need_to_change_language")}
              <select
                onChange={(e) => changeLocale(i18n, e.target.value)}
                className="outline-none border-none appearance-none pr-8"
              >
                <option>{t("en")}</option>
                <option>{t('fr')}</option>
              </select>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}

export default Login;

// backend/src/views/Login.vue
<template>
<section class="bg-white h-screen flex items-center max-w-lg mx-auto">
  <div class="flex items-center justify-center flex-col mx-auto shadow py-12 p-5 w-full">
      <div class="flex w-full justify-center">
        <a class="" href="/">
          <img src="../assets/logo.svg" class="w-16" />
        </a>
        <h1 class="mt-3 text-xl font-bold text-red-700">
            AvoRed Rust CMS
        </h1>
    </div>
    <div class="flex w-full">
        <form @submit.prevent="submit" action="#" class="mt-3 w-full">
          <div class="w-full">
            <label for="Email" class="w-full text-sm font-medium text-gray-700">
              Email
            </label>

            <input
              type="email"
              v-model="email"
              autofocus
              id="Email"
              name="email"
              class="mt-1 block w-full rounded-md border-gray-200 bg-white text-sm text-gray-700 shadow-sm"
            />
          </div>

          <div class="mt-5">
            <label
              for="Password"
              class="block text-sm font-medium text-gray-700"
            >
              Password
            </label>

            <input
              type="password"
              id="Password"
              v-model="password"
              name="password"
              class="mt-1 w-full rounded-md border-gray-200 bg-white text-sm text-gray-700 shadow-sm"
            />
          </div>

          <div class="mt-5 flex w-full items-center">
            <button
              type="submit"
              class="shrink-0 rounded-md border border-blue-600 bg-blue-600 px-8 py-3 text-sm font-medium text-white transition hover:bg-transparent hover:text-blue-600 focus:outline-none focus:ring active:text-blue-500"
            >
              Login
            </button>

            <p class="ml-auto text-sm text-gray-500">
              <a href="#" class="text-gray-700 underline">forgot your password?</a>.
            </p>
          </div>
        </form>
      </div>
  </div>
</section>
</template>


<script setup lang="ts">
import { AxiosResponse } from 'axios'
import { ref } from 'vue'
import type { Ref } from 'vue'
import avoredRustApi from '../api'
import { useRouter } from 'vue-router';


type AuthResponseType = {
  status: string,
  token: string
}

const router = useRouter()
const email: Ref<string> = ref('admin@admin.com')
const password: Ref<string> = ref('admin123')

const submit = async () => {
  
  const data = {email: email.value, password: password.value}
  
  const result: AxiosResponse<AuthResponseType> = await avoredRustApi.post(
      '/api/auth/login', 
      JSON.stringify(data),
      {
        headers: {
          'Content-Type': 'application/json'
        }
      });

  if (result.data.token) {
      localStorage.setItem('is_logged_in', 'true')
      localStorage.setItem('token', result.data.token)
      router.push({ path: '/' })

  }
}


</script>
