// backend/src/views/Login.vue
<template>
<section class="bg-white h-screen flex items-center max-w-lg mx-auto">
  <div class="flex items-center justify-center flex-col mx-auto shadow py-12 p-5 w-full">
      <div class="flex w-full justify-center">
        <a class="" href="/">
          <img src="../assets/logo.svg" class="w-16" />
        </a>
        <h1 class="mt-3 text-xl font-bold text-red-700">
            AvoRed Rust CMS
        </h1>
    </div>
    <div class="flex w-full">
        <form @submit.prevent="submit" action="#" class="mt-3 w-full">
          <div class="w-full">
            <label for="Email" class="w-full text-sm font-medium text-gray-700">
              Email
            </label>

            <input
              type="email"
              v-model="email"
              autofocus
              id="Email"
              name="email"
              class="mt-1 block w-full rounded-md border-gray-200 bg-white text-sm text-gray-700 shadow-sm"
            />
          </div>

          <div class="mt-5">
            <label
              for="Password"
              class="block text-sm font-medium text-gray-700"
            >
              Password
            </label>

            <input
              type="password"
              id="Password"
              v-model="password"
              name="password"
              class="mt-1 w-full rounded-md border-gray-200 bg-white text-sm text-gray-700 shadow-sm"
            />
          </div>

          <div class="mt-5 flex w-full items-center">
            <button
              type="submit"
              class="shrink-0 rounded-md border border-blue-600 bg-blue-600 px-8 py-3 text-sm font-medium text-white transition hover:bg-transparent hover:text-blue-600 focus:outline-none focus:ring active:text-blue-500"
            >
              Login
            </button>

            <p class="ml-auto text-sm text-gray-500">
              <a href="#" class="text-gray-700 underline">forgot your password?</a>.
            </p>
          </div>
        </form>
      </div>
  </div>
</section>
</template>


<script setup lang="ts">
import { AxiosResponse } from 'axios'
import { ref } from 'vue'
import type { Ref } from 'vue'
import api from '../api'
import { useRouter } from 'vue-router';


type AuthResponseType = {
  status: string,
  token: string
}

const router = useRouter()
const email: Ref<string> = ref('admin@admin.com')
const password: Ref<string> = ref('admin123')

const submit = async () => {
  console.log(email.value, password.value)
  const data = {email: email.value, password: password.value}
  
  const result: AxiosResponse<AuthResponseType> = await api.post(
      '/api/auth/login', 
      JSON.stringify(data),
      {
        headers: {
          'Content-Type': 'application/json'
        }
      });

  if (result.data.token) {
      localStorage.setItem('is_logged_in', 'true')
      router.push({ path: '/' })

  }
  console.log(result)
}


</script>

// react-admin/src/pages/auth/Login.jsx
import {useState} from "react";
import logo from "../../assets/logo_only.svg";
import {useNavigate} from "react-router-dom";

function Login() {
    const [email, setEmail] = useState('admin@admin.com');
    const [password, setPassword] = useState('admin123');
    const redirect = useNavigate()
    const handleSubmit = (async (e) => {
        e.preventDefault()
        console.log("handle submit")
        const response = (await fetch('http://localhost:8080/api/login', {
            method: 'post',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({email: email, password: password})
        }))
        const login_response = await response.json()
        console.log(login_response)
        if (login_response.status) {
            localStorage.setItem("AUTH_TOKEN", login_response.data)
            return redirect("/admin");
        }
    })


    return (
        <div
            className="min-h-screen bg-slate-100 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
            <div className="flex justify-center">
                <img src={logo} className="w-20 h-20" alt="Avored Rust Cms"/>
            </div>

            <div className="sm:mx-auto sm:w-full sm:max-w-md">
                <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
                    Sign into your account
                </h2>
            </div>
            <div>

            </div>

            <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
                <div className="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
                    <form onSubmit={handleSubmit} className="space-y-5" action="/admin/login" method="POST">
                        <div>
                            <label htmlFor="email_address" className="text-sm text-gray-600">
                                Email Address
                            </label>
                            <div className="mt-1">
                                <input
                                    type="email"
                                    name="email"
                                    required
                                    value={email}
                                    onChange={e => setEmail(e.target.value)}
                                    autoFocus
                                    className="appearance-none rounded-md ring-1 ring-primary-300 relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-primary-500 sm:text-sm focus:z-10"
                                    placeholder="Email Address"
                                />
                            </div>
                        </div>
                        <div>
                            <label htmlFor="password" className="text-sm text-gray-600">
                                Password
                            </label>
                            <div className="mt-1">
                                <input
                                    type="password"
                                    name="password"
                                    required
                                    value={password}
                                    onChange={e => setPassword(e.target.value)}
                                    className="appearance-none rounded-md ring-1 ring-primary-300 relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-primary-500 sm:text-sm focus:z-10"
                                    placeholder="Password"
                                />
                            </div>
                        </div>

                        <div className="flex items-center justify-end">
                            <div className="text-sm">
                                <a href="#"
                                   className="font-medium text-primary-600 hover:text-primary-500">
                                    Forgot your password?
                                </a>
                            </div>
                        </div>

                        <div>
                            <button type="submit"
                                    className="group relative bg-primary-600 w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
                            >
                                Sign in
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    )
}

export default Login
