// backend/src/views/role/RoleEdit.vue
<template>
  <div class="mx-auto max-w-screen-xl mt-3 mb-5">
    <div class="sm:flex sm:items-center sm:justify-between">
      <div class="text-center sm:text-left">
        <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">
          Edit Role
        </h1>
      </div>
    </div>
  </div>

  <div class="text-left border-t my-8 text-sm">
    <form @submit.prevent="submit" action="#" class="mt-3 w-full">
      <div class="w-full">
        <label for="name" class="w-full text-sm font-medium text-gray-700">
          Name
        </label>

        <input type="text" 
          v-model="edit_form.name"
          autofocus 
          id="name" 
          @blur="validation.name.$touch()"
          class="mt-1 block w-full rounded-md border-gray-200 bg-white text-sm text-gray-700 shadow-sm"
        />
          <div class="text-sm text-red-700" v-if="validation.name.$error && validation.name.required.$invalid">
            {{ validation.name.required.$message }}
          </div>
          
      </div>
      <div class="w-full">
        <label for="description" class="w-full text-sm font-medium text-gray-700">
          Description
        </label>

        <input type="text" 
          v-model="edit_form.description"
          id="description" 
          @blur="validation.description.$touch()"
          class="mt-1 block w-full rounded-md border-gray-200 bg-white text-sm text-gray-700 shadow-sm"
        />
      </div>

      <div class="mt-5 flex w-full items-center">
        <router-link class="mr-auto btn btn-default" :to="{name:'role-list'}">
          Cancel
        </router-link>

        <button type="submit" :disabled="!validation.$dirty || validation.$error"
          class="btn btn-primary">
          Edit Role
        </button>
        
      </div>
    </form>

  </div>
</template>
<script setup lang="ts">
import useVuelidate from '@vuelidate/core'
import { computed, onMounted, ref } from 'vue'
import { required } from '@vuelidate/validators'
import { AxiosResponse } from 'axios'
import avoRedRustApi from '../../api'
import { useRouter, useRoute } from 'vue-router'


const router = useRouter()
const route = useRoute()
const edit_form = ref<RoleType>({name: '', description: '', id: ''})
const rules =  computed(() => ({
      name: {
        required,
        $autoDirty: true
      },
    }))

  onMounted(async () => {

    const role_id = route.params.role_id
    const token = localStorage.getItem('token')
    const response: AxiosResponse<RoleType> = await avoRedRustApi.get(
        '/api/role/' + role_id,
        {
            headers: {
                "Authorization": `Bearer ${token}`,
                'Content-Type': 'application/json'
            }
        })

    edit_form.value = response.data

})


const validation =  useVuelidate(rules, edit_form)

const submit = async () => {

  const data = {name: edit_form.value.name, description: edit_form.value.description}

  const token = localStorage.getItem('token')
  const result: AxiosResponse<RoleType> = await avoRedRustApi.put(
      '/api/role/' + edit_form.value.id, 
      JSON.stringify(data),
      {
        headers: {
          "Authorization": `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });

  if (result.data.id) {
      router.push({ name: 'role-list' })
  }
}
interface RoleType {
    id: String,
    name: String,
    description: String,
}

</script>

// react-admin/src/pages/role/RoleEdit.jsx
import {useEffect, useState} from "react";
import {Link, useNavigate, useParams} from "react-router-dom";
import {isEmpty} from "lodash";
import axios from "axios";

function RoleEdit() {
    const [name, setName] = useState('Contact US update');
    const [identifier, setIdentifier] = useState('contact-us-update');
    const navigate = useNavigate()
    const params = useParams();


    useEffect(() => {
        const mounted = (async () => {
            const response = await axios({
                url: 'http://localhost:8080/api/role/' + params.role_id,
                method: 'get',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': 'Bearer ' + localStorage.getItem("AUTH_TOKEN"),
                }
            })

            if (!response.status) {
                return
            }

            return response.data
        })

        mounted().then((res) => {
            if (isEmpty(res)) {
                localStorage. removeItem("AUTH_TOKEN")
                return navigate("/admin/login")
            }

            setName(res.role_model.name)
            setIdentifier(res.role_model.identifier)
        })

    }, [])

    const handleSubmit = (async (e) => {
        e.preventDefault()
        const updated_role_response = await axios({
            url: 'http://localhost:8080/api/role/' + params.role_id, 
            method: 'put',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer ' + localStorage.getItem("AUTH_TOKEN"),
            },
            data: JSON.stringify({name: name, identifier: identifier, permissions: []})
        })
        if (updated_role_response.status) {
            return navigate("/admin/role");
        }
    })

    return (
        <div className="flex-1 bg-white">
            <div className="px-5 pl-64">
                <div className="w-full">
                    <div className="block rounded-lg p-6">
                        <h1 className="text-xl font-semibold mb-4 text-gray-900 dark:text-gray-100">
                            Role Information
                        </h1>
                        {/*<p className="text-gray-600 dark:text-gray-300 mb-6">Use a permanent address where you can*/}
                        {/*    receive mail.</p>*/}
                        <form onSubmit={handleSubmit}>
                            <div className="mb-4">
                                <input type="text" placeholder="Name"
                                       value={name}
                                       onChange={e => setName(e.target.value)}
                                       className="border p-2 rounded w-full"/>
                            </div>
                            <div className="mb-4">
                                <input type="text"
                                       placeholder="Identifier"
                                       value={identifier}
                                       onChange={e => setIdentifier(e.target.value)}
                                       className="border p-2 rounded w-full"/>
                            </div>
                            <div className="flex items-center">
                                <button type="submit"
                                        className="bg-primary-600 py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
                                >
                                    Save
                                </button>
                                <Link to="/admin/role"
                                      className="ml-auto font-medium text-gray-600 hover:text-gray-500">
                                    Cancel
                                </Link>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default RoleEdit
